import 'package:telehealthcare/drawer_screens/make_appoiment.dart';

final doctorMapList = [
  {
    "name": "Dr. Ahmed Mamdouh\nEldarandaly",
    "type": "Heart Sergeon",
    "rating": 4.9,
    "goodReviews": 95,
    "totalScore": 97,
    "satisfaction": 95.2,
    "isfavourite": true,
    "image": "assets/ahmed.png",
    "description": " ",
    "email": 'ahmedmamdouh430@gmail.com'
  },
  {
    "name": "Dr. Ibrhaim Ahmed",
    "type": "Neurology",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/ibra.jpg",
    "description": " ",
    "email": "IbrahimAmin@gmail.com"
  },
  {
    "name": "Dr. Mostada Sami",
    "type": "Cardio Sergeon",
    "rating": 2.5,
    "goodReviews": 69.420,
    "totalScore": 69.420,
    "satisfaction": 69.420,
    "isfavourite": false,
    "image": "assets/samy.jpg",
    "description": " ",
    "email": "sami@gmail.com"
  },
  {
    "name": "Dr. Ahmed Abdelbary",
    "type": "Heart Sergeon",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/bary1.jpg",
    "description": " ",
  },
  {
    "name": "Dr.Mostafa Abbas",
    "type": "Cardio Sergeon",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/profile.jpg",
    "description": " ",
  },
  {
    "name": "Dr.Abdelrhamn Hossam",
    "type": "Neurology",
    "rating": 4.0,
    "goodReviews": 75.2,
    "totalScore": 65,
    "satisfaction": 70,
    "isfavourite": true,
    "image": "assets/profile.jpg",
    "description": " ",
  },
  {
    "name": "Dr. Zaid Khaled",
    "type": "Neurology",
    "rating": 4.0,
    "goodReviews": 75.2,
    "totalScore": 65,
    "satisfaction": 70,
    "isfavourite": true,
    "image": "assets/profile.jpg",
    "description": " ",
  },
];
final patientMapList = [
  {
    "name": "Ahmed Mamdouh\nEldarandaly",
    "type": "Patient 1",
    "rating": 4.9,
    "goodReviews": 95,
    "totalScore": 97,
    "satisfaction": 95.2,
    "isfavourite": true,
    "image": "assets/ahmed.png",
    "description": "Patient 1",
    "email": 'ahmedmamdouh430@gmail.com'
  },
  {
    "name": "Mostada Sami",
    "type": "Patient 2",
    "rating": 2.5,
    "goodReviews": 69.420,
    "totalScore": 69.420,
    "satisfaction": 69.420,
    "isfavourite": false,
    "image": "assets/samy.jpg",
    "description": "Patient 2",
    "email": 'sami@gmail.com'
  },
  {
    "name": "Ibrhaim Ahmed",
    "type": "Patient 3",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/ibra.jpg",
    "description": "Patient 3",
    "email": 'IbrahimAmin@gmail.com'
  },
  {
    "name": "Ahmed Abdelbary",
    "type": "Patient 4",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/bary1.jpg",
    "description": "Patient 4",
  },
  {
    "name": "Mostafa Abbas",
    "type": "Patient 5",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/profile.jpg",
    "description": "Patient 5",
  },
  {
    "name": "Abdelrhamn Hossam",
    "type": "Patient 6",
    "rating": 4.0,
    "goodReviews": 75.2,
    "totalScore": 65,
    "satisfaction": 70,
    "isfavourite": true,
    "image": "assets/profile.jpg",
    "description": "Patient 6",
  },
  {
    "name": "Zaid Khaled",
    "type": "Patient 7",
    "rating": 4.0,
    "goodReviews": 75.2,
    "totalScore": 65,
    "satisfaction": 70,
    "isfavourite": true,
    "image": "assets/profile.jpg",
    "description": "Patient 7",
  },
];
