import 'package:telehealthcare/drawer_screens/make_appoiment.dart';

final doctorMapList = [
  {
    "name": "Eng. Ahmed Mamdouh\nEldarandaly",
    "type": "Software Engineer",
    "rating": 4.9,
    "goodReviews": 95,
    "totalScore": 97,
    "satisfaction": 95.2,
    "isfavourite": true,
    "image": "assets/ahmed.png",
    "description": "الدرندلي واحد بس",
    "email": 'ahmedmamdouh430@gmail.com'
  },
  {
    "name": "Eng Ibrhaim Ahmed",
    "type": "Software Engineer",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/ibra.jpg",
    "description": "Top ج",
    "email": "IbrahimAmin@gmail.com"
  },
  {
    "name": "Mostada Sami",
    "type": "علقوي",
    "rating": 2.5,
    "goodReviews": 69.420,
    "totalScore": 69.420,
    "satisfaction": 69.420,
    "isfavourite": false,
    "image": "assets/sami.png",
    "description": "العلق",
    "email": "sami@gmail.com"
  },
  {
    "name": "Ahmed Abdelbary",
    "type": "Not good enough",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/bary.jpeg",
    "description": "Top ج",
  },
  {
    "name": "Mostafa Abbas",
    "type": "عبوو",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/abbas.jpg",
    "description": "Top ج",
  },
  {
    "name": "Abdelrhamn Mohamed",
    "type": "senior computer engineer",
    "rating": 4.0,
    "goodReviews": 75.2,
    "totalScore": 65,
    "satisfaction": 70,
    "isfavourite": true,
    "image": "assets/doctor_1.png",
    "description": " ",
  },
  {
    "name": "Zaid Ahmed",
    "type": "senior computer engineer",
    "rating": 4.0,
    "goodReviews": 75.2,
    "totalScore": 65,
    "satisfaction": 70,
    "isfavourite": true,
    "image": "assets/doctor_3.png",
    "description": " ",
  },
];
final patientMapList = [
  {
    "name": "Ahmed Mamdouh\nEldarandaly",
    "type": "مريض 1",
    "rating": 4.9,
    "goodReviews": 95,
    "totalScore": 97,
    "satisfaction": 95.2,
    "isfavourite": true,
    "image": "assets/ahmed.png",
    "description": "الدرندلي واحد بس",
    "email": 'ahmedmamdouh430@gmail.com'
  },
  {
    "name": "Mostada Sami",
    "type": "مريض 3",
    "rating": 2.5,
    "goodReviews": 69.420,
    "totalScore": 69.420,
    "satisfaction": 69.420,
    "isfavourite": false,
    "image": "assets/sami.png",
    "description": "العلق",
    "email": 'sami@gmail.com'
  },
  {
    "name": "Ibrhaim Ahmed",
    "type": "مريض 2",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/ibra.jpg",
    "description": "Top ج",
    "email": 'IbrahimAmin@gmail.com'
  },
  {
    "name": "Ahmed Abdelbary",
    "type": "مريض 4",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/bary.jpeg",
    "description": "Never Ever good enough",
  },
  {
    "name": "Mostafa Abbas",
    "type": "عبوو",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/abbas.jpg",
    "description": " ",
  },
  {
    "name": "Abdelrhamn Mohamed",
    "type": "senior computer engineer",
    "rating": 4.0,
    "goodReviews": 75.2,
    "totalScore": 65,
    "satisfaction": 70,
    "isfavourite": true,
    "image": "assets/doctor_1.png",
    "description": " ",
  },
  {
    "name": "Zaid Ahmed",
    "type": "senior computer engineer",
    "rating": 4.0,
    "goodReviews": 75.2,
    "totalScore": 65,
    "satisfaction": 70,
    "isfavourite": true,
    "image": "assets/doctor_3.png",
    "description": " ",
  },
];
