final doctorMapList = [
  {
    "name": "Eng. Ahmed Mamdouh\nEldarandaly",
    "type": "Software Engineer",
    "rating": 4.9,
    "goodReviews": 95,
    "totalScore": 97,
    "satisfaction": 95.2,
    "isfavourite": true,
    "image": "assets/ahmed.png",
    "description": "الدرندلي واحد بس",
  },
  {
    "name": "Eng Ibrhaim Ahmed",
    "type": "Software Engineer",
    "rating": 4.9,
    "goodReviews": 95.2,
    "totalScore": 96,
    "satisfaction": 96,
    "isfavourite": true,
    "image": "assets/ibra.jpg",
    "description": "Top ج",
  },
  {
    "name": "Mostada Sami",
    "type": "علقوي",
    "rating": 2.5,
    "goodReviews": 69.420,
    "totalScore": 69.420,
    "satisfaction": 69.420,
    "isfavourite": false,
    "image": "assets/sami.png",
    "description": "العلق",
  },
  // {
  //   "name": "Dr. Bruce Banner",
  //   "type": "Heart Sergeon",
  //   "rating": 1.5,
  //   "goodReviews": 12.2,
  //   "totalScore": 75.2,
  //   "satisfaction": 84.2,
  //   "isfavourite": true,
  //   "image":"assets/doctor_1.png",
  //   "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  // }
];
